### ISSUE TITLE
Support Cache Busting

### ISSUE THREAD

**Issue by muellercornelius** [rishabh3112/gridsome-plugin-pwa#24]
I like this plugin really much and it is working great. 

One Problem is that the Cache gets never cleared even when changing something and a full page reload. (Of course only in Production)

Would it be possible to supply the service worker with a version number or anything like that so the browser clears the cache and downloads all changed files?

**Comment by rishabh3112** [comment]
Hi @muellercornelius,
Thanks for compliment.
Would you want to implement it? feel free to send a PR, I would be happy to help you out!

**Comment by muellercornelius** [comment]
I will try it ;)

**Comment by hacknug** [comment]
Maybe it could rely on core's [`cacheBusting`](https://github.com/gridsome/gridsome/pull/840#issuecomment-559528336) option? Not completely sure it makes sense to keep them tied or not though

**Comment by preetamslot** [comment]
Had the same issue, so I updated 2 files in this repo:

**in the utils/skip-waiting.js**

```
addEventListener('message', (event) => {
  console.log('event', event);
  if (event.data && event.data.type === 'SKIP-WAITING') {
      caches.keys().then(function(cacheNames) {
        return Promise.all(
          cacheNames.filter(function(cacheName) {
           //  filter is used if you don't want to delete all files. return true to remove
           return true
          }).map(function(cacheName) {
            return caches.delete(cacheName);
          })
        );
      })
    self.skipWaiting();
  }
});
```


and in the updated function **gridsome.client.js**

```
updated (registration) {
        console.log('New content is available; please refresh.') 
          registration.waiting.postMessage({ type: 'SKIP-WAITING' });  
      },
 
```

**Comment by muellercornelius** [comment]
@preetamslot  Did you replaced all Code in skip-waiting.js or did you just added this code?

**Comment by muellercornelius** [comment]
After Digging in the documentation and a lot trial and error I found the solution.

A new Service Worker was registered but it didnt replace the previous Service Worker. Thats whats Skip Waiting is doing. 

So we simply need to call it. The Code for that was already provided by @preetamslot 

```
updated (registration) {
        console.log('New content is available; please refresh.') 
          registration.waiting.postMessage({ type: 'SKIP-WAITING' });  
      },
```
This Code is enough to make it work. When Skip Waiting is called Workbox determines automatically which of the files is updated and only requests those files.

**Comment by muellercornelius** [comment]
My fault I was wrong. It is not enough to simply call SKIP Waiting. It improves it so the service worker gets activated but the cache is not cleared ;(. We should integrate @preetamslot solution as well. But its pretty radical to delete the whole cache... or am I wrong? 

In offline mode this is not a problem because the User dont get notified about a new service worker... So the cache is persisted...

Some other thoughts?
