### ISSUE TITLE
ReferenceError: options is not defined

### ISSUE THREAD

**Issue by acidiney** [rishabh3112/gridsome-plugin-pwa#3]
Hi,

I have installed this plugin in my gridsome app, and have configured. But when I run the command `gridsome develop`, I site starter blank and I receive this message

![image](https://user-images.githubusercontent.com/24493328/61791301-8628ab00-ae11-11e9-8c06-f8c7510ff60a.png)

If I run `gridsome build`, this error message appears at the end of the process
![image](https://user-images.githubusercontent.com/24493328/61791360-ae180e80-ae11-11e9-88a7-24b75a1bf991.png)

this is my plugin configuration: 
```js
plugins: [
    {
      use: 'gridsome-plugin-pwa',
      options: {
        title: 'Digital Factory',
        startUrl: '/',
        display: 'standalone',
        statusBarStyle: 'default',
        manifestPath: 'manifest.json',
        serviceWorkerPath: 'service-worker.js',
        shortName: 'Digital Factory',
        themeColor: '#000',
        backgroundColor: '#fdd348',
        icon: 'lgo.png'
      }
    }
  ]
```

I have created a `service-worker,js` and `manifest.json` in the static folder

Thanks

**Comment by rishabh3112** [comment]
Hi @acidiney, thanks for reporting!
Have pushed the patch to fix this and many other errors and available at v0.0.5.
Few other issues for you to fix:
1. Use location of icon relative to the root folder (not the src folder)
2. manifest and service will be generated by the plugin itself.

> Note: manifest and service worker will only be generated during production build.

Hopes that solves the issue. Keep giving feedbacks ;)
