### ISSUE TITLE
Favicon Checker Improvements

### ISSUE THREAD

**Issue by RehanSaeed** [rishabh3112/gridsome-plugin-pwa#35]
The real favicon generator has a page that can check your site configuration. Here is mine:

https://realfavicongenerator.net/favicon_checker?protocol=https&site=preview.rehansaeed.com

You can see that there are a few missing images for iOS, MacOS and Windows 10. It would be nice if these were also included.

**Comment by rishabh3112** [comment]
Hi, feel free to send PR.

**Comment by rishabh3112** [comment]
This is solved, closing...
