### ISSUE TITLE
Bad Precaching Response

### ISSUE THREAD

**Issue by Matthew-Kanderka** [rishabh3112/gridsome-plugin-pwa#4]
Hi,

When hosting in production I receive the following error below during the service-worker setup.

![image](https://user-images.githubusercontent.com/38925860/62546511-d85dc900-b820-11e9-85d4-8950eeb63dbf.png)

Here is the repo.

https://github.com/Matthew-Kanderka/hummingbird-Airsoft-Web/tree/develop

Before I got this issue I was receiving a DOMException. This is what my gridsome.config.js file looks like,

![image](https://user-images.githubusercontent.com/38925860/62547382-5e2e4400-b822-11e9-9864-a56d61d78beb.png)

I also have a question about customizing the service worker, are we able to configure it or is it only auto generated?

Thanks

**Comment by Matthew-Kanderka** [comment]
The 403 may be due to being behind a proxy, since I tried the site not from home but still curious about whether you can customize the service-worker as it doesn't look like it is caching my webp images.

**Comment by Matthew-Kanderka** [comment]
Ok I am still having this issue not on a proxy, why is the client.json being generated?

**Comment by rishabh3112** [comment]
`assets/manifest/client.json` is not generated in the final build (in your case too). It's an immediate file generated by gridsome itself while running the plugin. But `service-worker.js` seems to have it (that shouldn't have any visual impact though).

Would be nice if you send a PR with the fix here: https://github.com/rishabh3112/gridsome-plugin-pwa/blob/5d830ccc4bca338817e213930880142b476f25ad/src/files/service-worker.js#L17

P.S.
Sorry for the late reply was busy with university stuff.

**Comment by Matthew-Kanderka** [comment]
No worries, I'll for sure send you a pull for the fix. I was thinking should we just remove the json pattern or we could make the list a parameter in the plugin options, what do you think?

**Comment by rishabh3112** [comment]
Thanks for understanding,
We must not remove `json` from the pattern, instead you can add files to ignore in the `globIgnores` below the line I quoted above.
And yes we can take this from user as a plugin parameter, but this must include `client.json` ( w/o relying on the user to input).

**Comment by Matthew-Kanderka** [comment]
Ok sounds good. Just out of curiosity how did you test this locally. I built the plugin and then created a folder in my gridsome website, moved the files there and then changed the path of the plugin in gridsome.config.

**Comment by rishabh3112** [comment]
Pass absolute path of the plugin folder as plugin's name in the gridsome config.

**Comment by rishabh3112** [comment]
Solved at #5

**Comment by rishabh3112** [comment]
Will release as soon as I get free time :)

**Comment by rishabh3112** [comment]
Changes published under v0.0.6

**Comment by Matthew-Kanderka** [comment]
Hey, I just tried to update to the new version and when I did I noticed that my changes are not there but the version is 0.0.6

![image](https://user-images.githubusercontent.com/38925860/63486185-a628aa00-c463-11e9-87a5-c8ab01464e40.png)

![image](https://user-images.githubusercontent.com/38925860/63486195-b50f5c80-c463-11e9-9266-c706cfc8c091.png)

**Comment by rishabh3112** [comment]
Ohh, thanks for identifying. Forgot to build in hurry!
V0.0.7 have this!

**Comment by preetamslot** [comment]
Could it be that the server.json should also be on the ignore list?

` globIgnores: [options.serviceWorkerPath, '**\/*client.json','**\/*server.json'],`

![image](https://user-images.githubusercontent.com/5420582/64539289-8972ea00-d31e-11e9-8cb3-b5b31a1dee1e.png)
Thanks

**Comment by rishabh3112** [comment]
Yes @preetamslot, PR for that has been merged. Will be releasing soon as soon as I am free.
