### ISSUE TITLE
Incorrect path of msapplication-TileImage

### ISSUE THREAD

**Issue by hendrikbursian** [rishabh3112/gridsome-plugin-pwa#48]
While checking for broken links with [hyperlink](https://www.npmjs.com/package/hyperlink) after I build my website, I noticed that the path for the `msapplication-TileImage` is broken no matter the configuration.

**hyperlink output**
```
...
not ok 2 load dist/assets/static/favicon.png-144x144.png
  ---
    operator: load
    expected:
      "200 dist/assets/static/favicon.png-144x144.png"
    actual:
      "ENOENT: no such file or directory, open '[HIDDEN]/dist/assets/static/favicon.png-144x144.png'"
    at: dist/index.html:4:987 <meta data-vue-tag="ssr" name="msapplication-TileImage" content="/assets/static/favicon.png-144x144.png">
...
```

The generated path is `dist/assets/static/favicon.png-144x144.png` but it should be `dist/assets/static/favicon-144x144.png`.

I looked up the code that generates the path and found what is wrong with it:

```js
  const iconsDir = 'assets/static/';
  const iconName = options.icon.split('/').slice(-1)[0]; // <-- Here the whole filename is taken (i.e. "favicon.png")
  const msTileImage = `/${iconsDir}${iconName}-144x144.png`; // Which then results in "/assets/static/favicon.png-144x144.png", instead of "/assets/static/favicon-144x144.png"
```
[source](https://github.com/rishabh3112/gridsome-plugin-pwa/blob/129075424d97a4b34725db3ed5a4b7edade93672/gridsome.client.js#L32
)

**Comment by hendrikbursian** [comment]
I'm already working on a fix, it would be nice if you could merge it, if I did not overlook somethting major here :)

**Comment by rishabh3112** [comment]
Thanks for pull request!
