### ISSUE TITLE
Wrong Icons are generated in built Manifest.json file

### ISSUE THREAD

**Issue by Edmund1645** [rishabh3112/gridsome-plugin-pwa#8]
I ran `gridsome build` to see how the directories look after building for production because I noticed that I don't get the dialog to 'add to homescreen', An array of all images in src is what's passed as icons instead of the one I put in `/static`

sample of `manifest.json` file
![Screenshot from 2019-08-30 20-57-52](https://user-images.githubusercontent.com/34253790/64048511-d1994c00-cb69-11e9-88c1-59f7e4515853.png)

what i specified in `gridsome.config.js`
![Screenshot from 2019-08-30 20-58-02](https://user-images.githubusercontent.com/34253790/64048578-fd1c3680-cb69-11e9-956b-87878dc472c2.png)
I also changed how I linked to the icon but that still gave the same result.

**Comment by Edmund1645** [comment]
also I noticed that a `service-worker.js` file that does nothing is generated in the root directory, and the content of that file keeps duplicating any time I run build.

**Comment by rishabh3112** [comment]
Please share minimum reproducible repository.

**Comment by Edmund1645** [comment]
> Please share minimum reproducible repository.

I don't understand please, like a link to my repository where the entire project is?

**Comment by rishabh3112** [comment]
Yes. If you don't want to, you may reproduce the error in minimum possible files, upload to gothub and share it here.
Thanks!

**Comment by IHIutch** [comment]
This has been noted here: https://github.com/gridsome/gridsome/issues/167#issuecomment-516840467

You can see my [manifest.json](https://github.com/gridsome/gridsome/issues/167#issuecomment-516840467) and see that an icon is generated for every image on my site, rather than just the icon I specify in my [gridsome.config.js](https://github.com/IHIutch/bufgreencode_gridsome/blob/master/gridsome.config.js)

**Comment by rishabh3112** [comment]
Hi @Edmund1645 and @IHIutch, I have pushed the patch with the fix. let me know if it's a issue anymore.

**Comment by IHIutch** [comment]
Looks like its working to me :)

**Comment by dizid** [comment]
Hi, 
I have spent some time trying to debug this, but don't know what i could do.
After `$ npm install gridsome-plugin-pwa` and configuring` gridsome.config.js` i get this error on 
`$ gridsome develop`:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1144:5)
```

**Comment by Edmund1645** [comment]
The location you set to your icon has to be absolute, so it should start with `static/`

**Comment by rishabh3112** [comment]
In addition, @dizid you may open a new issue for this as this issue isn't related to your problem.

**Comment by dizid** [comment]
Thank you @Edmund1645 
I have tried dozens of variations and location, same error.
with a ./ and without, different file locations etc.

@rishabh3112 I have been solving a few different issues for 2 days now, time to move on.
