### ISSUE TITLE
service-worker.js being created in root directory

### ISSUE THREAD

**Issue by IHIutch** [rishabh3112/gridsome-plugin-pwa#9]
Making a new issue for [this comment](https://github.com/rishabh3112/gridsome-plugin-pwa/issues/8#issuecomment-526733655)

Not sure what it does or is supposed to do... Mine looks like this:

```
addEventListener('message', event => {
  const replyPort = event.ports[0]
  const message = event.data
  if (replyPort && message && message.type === 'skip-waiting') {
    event.waitUntil(
      self.skipWaiting().then(
        () => replyPort.postMessage({ error: null }),
        error => replyPort.postMessage({ error })
      )
    )
  }
})
```

This service worker is in addition to the one generated in `dist` which appears to be working correctly

**Comment by rishabh3112** [comment]
I have patched the fix for the bud @IHIutch, let me know if it does.

**Comment by IHIutch** [comment]
I don't see that file showing up anymore, looks good thanks!
